/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.internal.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param quantity 
 * @param unit Unit of measurement (e.g. g, ml, cup, tbsp)
 * @param name 
 */


data class RecipeIngredient (

    @Json(name = "quantity")
    val quantity: kotlin.Double,

    /* Unit of measurement (e.g. g, ml, cup, tbsp) */
    @Json(name = "unit")
    val unit: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String

) {


}

