/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.internal.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param calories Number of Calories (kcal)
 * @param protein Protein in grams
 * @param fat Fat in grams
 * @param carbs Carbohydrates in grams
 */


data class RecipeNutrients (

    /* Number of Calories (kcal) */
    @Json(name = "calories")
    val calories: kotlin.Int,

    /* Protein in grams */
    @Json(name = "protein")
    val protein: kotlin.Int,

    /* Fat in grams */
    @Json(name = "fat")
    val fat: kotlin.Int,

    /* Carbohydrates in grams */
    @Json(name = "carbs")
    val carbs: kotlin.Int

) {


}

