/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.internal.model

import org.openapitools.internal.model.RecipeIngredient
import org.openapitools.internal.model.RecipeNutrients

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * At least one field must be provided
 *
 * @param title 
 * @param ingredients 
 * @param instructions 
 * @param portions 
 * @param nutrients 
 */


data class RecipeUpdate (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "ingredients")
    val ingredients: kotlin.collections.List<RecipeIngredient>? = null,

    @Json(name = "instructions")
    val instructions: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "portions")
    val portions: kotlin.Double? = null,

    @Json(name = "nutrients")
    val nutrients: RecipeNutrients? = null

) {


}

