/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
	"ArrayInDataClass",
	"DuplicatedCode",
	"EnumEntryName",
	"RemoveRedundantQualifierName",
	"RemoveRedundantCallsOfConversionMethods",
	"REDUNDANT_CALL_OF_CONVERSION_METHOD",
	"RedundantUnitReturnType",
	"RemoveEmptyClassBody",
	"UnnecessaryVariable",
	"UnusedImport",
	"UnnecessaryVariable",
	"unused",
)

package org.openapitools.internal.model

import com.squareup.moshi.Json
import org.openapitools.internal.model.UserProfile

/**
 *
 *
 * @param profile
 * @param prompt
 */

data class RecipeRequestForwarded(
	@Json(name = "profile")
	val profile: UserProfile,
	@Json(name = "prompt")
	val prompt: kotlin.String,
)
