/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
	"ArrayInDataClass",
	"DuplicatedCode",
	"EnumEntryName",
	"RemoveRedundantQualifierName",
	"RemoveRedundantCallsOfConversionMethods",
	"REDUNDANT_CALL_OF_CONVERSION_METHOD",
	"RedundantUnitReturnType",
	"RemoveEmptyClassBody",
	"UnnecessaryVariable",
	"UnusedImport",
	"UnnecessaryVariable",
	"unused",
)

package org.openapitools.internal.model

import com.squareup.moshi.Json
import org.openapitools.internal.model.RecipeIngredient
import org.openapitools.internal.model.RecipeNutrients

/**
 *
 *
 * @param title
 * @param ingredients
 * @param instructions
 * @param portions
 * @param nutrients
 */

data class RecipeInput(
	@Json(name = "title")
	val title: kotlin.String,
	@Json(name = "ingredients")
	val ingredients: kotlin.collections.List<RecipeIngredient>,
	@Json(name = "instructions")
	val instructions: kotlin.collections.List<kotlin.String>,
	@Json(name = "portions")
	val portions: kotlin.Double,
	@Json(name = "nutrients")
	val nutrients: RecipeNutrients? = null,
)
