/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.internal.client

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.internal.client.HelpServiceApi
import org.openapitools.internal.model.ErrorResponse
import org.openapitools.internal.model.HealthGet200Response
import org.openapitools.internal.model.HelpRequestForwarded
import org.openapitools.internal.model.HelpResponse

class HelpServiceApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HelpServiceApi
        //val apiInstance = HelpServiceApi()

        // to test aiHelpPost
        should("test aiHelpPost") {
            // uncomment below to test aiHelpPost
            //val xInternalTimestamp : kotlin.String = xInternalTimestamp_example // kotlin.String | Linux Unix epoch timestamp string binding the generation window to block replay attacks.
            //val xInternalSignature : kotlin.String = xInternalSignature_example // kotlin.String | Hex-encoded HMAC-SHA256 signature validating data package integrity over private networks.
            //val helpRequestForwarded : HelpRequestForwarded =  // HelpRequestForwarded | 
            //val result : HelpResponse = apiInstance.aiHelpPost(xInternalTimestamp, xInternalSignature, helpRequestForwarded)
            //result shouldBe ("TODO")
        }

        // to test healthGet
        should("test healthGet") {
            // uncomment below to test healthGet
            //val result : HealthGet200Response = apiInstance.healthGet()
            //result shouldBe ("TODO")
        }

    }
}
