/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
	"ArrayInDataClass",
	"DuplicatedCode",
	"EnumEntryName",
	"RemoveRedundantQualifierName",
	"RemoveRedundantCallsOfConversionMethods",
	"REDUNDANT_CALL_OF_CONVERSION_METHOD",
	"RedundantUnitReturnType",
	"RemoveEmptyClassBody",
	"UnnecessaryVariable",
	"UnusedImport",
	"UnnecessaryVariable",
	"unused",
)

package org.openapitools.internal.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec
import org.openapitools.internal.model.RecipeIngredient
import org.openapitools.internal.model.RecipeNutrients
import org.openapitools.internal.model.RecipeUpdate

class RecipeUpdateTest : ShouldSpec() {
	init {
		// uncomment below to create an instance of RecipeUpdate
		// val modelInstance = RecipeUpdate()

		// to test the property `title`
		should("test title") {
			// uncomment below to test the property
			// modelInstance.title shouldBe ("TODO")
		}

		// to test the property `ingredients`
		should("test ingredients") {
			// uncomment below to test the property
			// modelInstance.ingredients shouldBe ("TODO")
		}

		// to test the property `instructions`
		should("test instructions") {
			// uncomment below to test the property
			// modelInstance.instructions shouldBe ("TODO")
		}

		// to test the property `portions`
		should("test portions") {
			// uncomment below to test the property
			// modelInstance.portions shouldBe ("TODO")
		}

		// to test the property `nutrients`
		should("test nutrients") {
			// uncomment below to test the property
			// modelInstance.nutrients shouldBe ("TODO")
		}
	}
}
