/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package org.openapitools.internal.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.internal.model.UserProfileUpdate
import org.openapitools.internal.model.UserPreferences

class UserProfileUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserProfileUpdate
        //val modelInstance = UserProfileUpdate()

        // to test the property `username` - Alphanumeric, underscores, hyphens, and dots only
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `preferences`
        should("test preferences") {
            // uncomment below to test the property
            //modelInstance.preferences shouldBe ("TODO")
        }

    }
}
