import asyncio
import hashlib
import hmac
import os
import time
import traceback
from typing import Any, List
from fastapi import Depends, FastAPI, HTTPException, Header, Request
from dotenv import load_dotenv
from fastapi.responses import JSONResponse
from langchain.chat_models import init_chat_model
from langchain_core.messages import HumanMessage, SystemMessage
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.sdk.resources import Resource, SERVICE_NAME
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from pydantic import BaseModel
from langchain_core.language_models.chat_models import BaseChatModel

from prometheus_fastapi_instrumentator import Instrumentator
from client.cooking_assistant_gen_ai_services_api_internal_client.models.recipe_request_forwarded import (
	RecipeRequestForwarded,
)

from client.cooking_assistant_gen_ai_services_api_internal_client.models.recipe_input import (
	RecipeInput,
)

from client.cooking_assistant_gen_ai_services_api_internal_client.models.nutrient_request_forwarded import (
	NutrientRequestForwarded,
)

# Load variables from .env for local testing
load_dotenv()

_otlp_base = os.getenv(
	"OTEL_EXPORTER_OTLP_ENDPOINT", "http://alloy.monitoring.svc.cluster.local:4318"
)
_provider = TracerProvider(
	resource=Resource.create({SERVICE_NAME: "py-recipe-service"})
)
_provider.add_span_processor(
	BatchSpanProcessor(OTLPSpanExporter(endpoint=f"{_otlp_base}/v1/traces"))
)
trace.set_tracer_provider(_provider)
_tracer = trace.get_tracer("py-recipe-service")

app = FastAPI(title="Cooking Assistant GenAI Service")
Instrumentator().instrument(app).expose(app)
FastAPIInstrumentor.instrument_app(app, excluded_urls="/health,/metrics")


# autogenerated classes must be mapped to local ones that are compatible with pydantic
class LocalRecipeIngredient(BaseModel):
	quantity: float
	unit: str
	name: str


class LocalRecipeNutrients(BaseModel):
	calories: int
	protein: int
	fat: int
	carbs: int


class LocalRecipeInput(BaseModel):
	title: str
	ingredients: List[LocalRecipeIngredient]
	instructions: List[str]
	portions: float
	nutrients: LocalRecipeNutrients  # required field here as llm can't handle optional fields reliably


# local wrapper for recipes - llms are optimized for producing json whereas api spec expects array of json
class RecipeListWrapper(BaseModel):
	recipes: List[LocalRecipeInput]


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
	body = exc.detail if isinstance(exc.detail, dict) else {"message": exc.detail}
	return JSONResponse(status_code=exc.status_code, content=body, headers=exc.headers)


LANGUAGE_NAMES = {"EN": "English", "DE": "German", "HU": "Hungarian"}

SECRET_KEY_STR = os.getenv("INTERNAL_AUTH_SECRET")
if not SECRET_KEY_STR:
	raise RuntimeError(
		"CRITICAL: INTERNAL_AUTH_SECRET environment variable is missing!"
	)

SECRET_KEY_BYTES = SECRET_KEY_STR.encode("utf-8")


async def verify_internal_hmac(
	request: Request,
	x_internal_timestamp: str = Header(None),
	x_internal_signature: str = Header(None),
):
	"""
	Validates that the incoming request contains an authentic HMAC signature bound to the timestamp and the request payload.
	Caution: Redundant versions of this method in py-help-service and py-recipe service.
	"""
	if not x_internal_timestamp or not x_internal_signature:
		raise HTTPException(
			status_code=401,
			detail={
				"message": "Unauthorized: Missing security authentication headers."
			},
		)

	# 1. Parse incoming timestamp string context securely
	try:
		request_time = int(x_internal_timestamp)
	except ValueError:
		raise HTTPException(
			status_code=400,
			detail={"message": "Invalid timestamp metadata formatting."},
		)

	# 2. Reject requests with more than 5 minutes of clock drift
	current_time = int(time.time())
	if abs(current_time - request_time) > 300:
		raise HTTPException(
			status_code=401, detail={"message": "Request token signature expired."}
		)

	# 3. Read the raw body bytes directly from the stream
	body_bytes = await request.body()

	# 4. Recalculate signature locally by hashing both pieces together
	# Using a separator byte like b'.' prevents boundary shifting bugs
	hmac_context = hmac.new(SECRET_KEY_BYTES, digestmod=hashlib.sha256)
	hmac_context.update(x_internal_timestamp.encode("utf-8"))
	hmac_context.update(b".")
	hmac_context.update(body_bytes)

	expected_signature = hmac_context.hexdigest()

	# 5. Use constant-time comparison to completely prevent timing attacks
	if not hmac.compare_digest(expected_signature, x_internal_signature):
		raise HTTPException(
			status_code=403,
			detail={"message": "Forbidden: HMAC signature validation mismatch."},
		)


def get_llm():
	"""
	Dynamically builds the correct LLM structure using environment variables.
	"""
	provider = os.getenv("PROVIDER", "google_genai")

	kwargs = {"timeout": 60}

	if provider == "local":
		kwargs["base_url"] = os.getenv(
			"LOCAL_BASE_URL", "http://host.docker.internal:1234/v1"
		)
		kwargs["api_key"] = os.getenv("LOCAL_KEY", "not-needed")
		kwargs["response_format"] = {"type": "json_object"}
		model_name = os.getenv("LOCAL_MODEL", "local-model")

		# We explicitly enforce the underlying OpenAI integration layout
		provider_target = "openai"

	elif provider == "openai":
		logos_key = os.getenv("LOGOS_KEY")
		if not logos_key:
			raise RuntimeError("CRITICAL: LOGOS_KEY is missing!")

		kwargs["base_url"] = os.getenv(
			"LOGOS_BASE_URL", "https://logos.aet.cit.tum.de/v1"
		)
		kwargs["api_key"] = logos_key
		kwargs["reasoning_effort"] = (
			"low"  # times out for medium and high, "minimal not supported by Harmony"
		)
		model_name = os.getenv("LOGOS_MODEL", "openai/gpt-oss-120b")

		provider_target = "openai"

	else:
		gemini_key = os.getenv("GEMINI_RECIPE_SERVICE_KEY")
		if not gemini_key:
			raise RuntimeError("CRITICAL: GEMINI_RECIPE_SERVICE_KEY is missing!")

		kwargs["google_api_key"] = gemini_key
		kwargs["thinking_level"] = (
			"low"  # inference time fluctuate a lot
			# minimal doesn't seem a lot faster than low but seemingly produces more mistakes in json output formatting
			# medium and high seem noticeably slower than low
		)
		model_name = os.getenv("GEMINI_MODEL", "gemini-3.1-flash-lite")

		provider_target = "google_genai"

	try:
		return init_chat_model(
			model=model_name, model_provider=provider_target, **kwargs
		)
	except Exception as e:
		raise RuntimeError(f"Failed to boot LLM provider '{provider}': {e}")


@app.get("/health")
def health_check():
	return {"status": "healthy"}


@app.post("/ai/recipes", dependencies=[Depends(verify_internal_hmac)])
async def generate_recipes(
	request_data: dict[str, Any], llm: BaseChatModel = Depends(get_llm)
):

	try:
		request = RecipeRequestForwarded.from_dict(request_data)
	except Exception as e:
		raise HTTPException(
			status_code=400, detail={"message": f"Invalid request format: {str(e)}"}
		)

	if not request.profile or not request.profile.preferences:
		raise HTTPException(
			status_code=400, detail={"message": "Missing required profile preferences."}
		)

	try:
		# 1. Extract Profile Context
		prefs = request.profile.preferences
		diet = ", ".join(prefs.diet) if prefs.diet else "None"
		allergies = ", ".join(prefs.allergies) if prefs.allergies else "None"
		about = ", ".join(prefs.about_me) if prefs.about_me else "None"
		language = LANGUAGE_NAMES.get(
			getattr(prefs.language, "value", None) or "EN", "English"
		)

		# 2. Build the System Prompt
		system_prompt = (
			"You are a professional chef. Create a collection of distinct high-quality recipes.\n"
			f"Constraint - Diet: {diet}\n"
			f"Constraint - Allergies: {allergies} (DO NOT USE THESE)\n"
			f"User Context: {about}\n\n"
			f"Write all recipe content (title, ingredients, units and instructions) in {language}. "
			"Strictly use standard, lowercase abbreviated unit names (e.g., use 'tbsp' instead of 'tablespoon', "
			"'tsp' instead of 'teaspoon', 'g' instead of 'grams', and 'ml' instead of 'milliliters').\n"
			"Output the nutrients for the whole recipe in total, not per portion.\n"
			f"Keep the JSON keys in English as specified."
		)

		structured_llm = llm.with_structured_output(RecipeListWrapper)

		# 3. Invoke LLM
		messages = [
			SystemMessage(content=system_prompt),
			HumanMessage(content=f"Generate 3 distinct recipes for: {request.prompt}"),
		]

		with _tracer.start_as_current_span("llm.generate_recipes"):
			response = await asyncio.wait_for(
				structured_llm.ainvoke(messages), timeout=60
			)

		# return array of recipes as expeted from the api spec
		final_recipes = []
		for r in response.recipes:
			recipe_dict = r.model_dump()
			final_recipes.append(RecipeInput.from_dict(recipe_dict))

		return [r.to_dict() for r in final_recipes]

	except asyncio.TimeoutError:
		raise HTTPException(
			status_code=504, detail={"message": "LLM connection timed out."}
		)
	except Exception as e:
		traceback.print_exc()
		raise HTTPException(status_code=500, detail={"message": str(e)})


@app.post("/ai/nutrients", dependencies=[Depends(verify_internal_hmac)])
async def generate_nutrients(
	request_data: dict[str, Any], llm: BaseChatModel = Depends(get_llm)
):
	try:
		request = NutrientRequestForwarded.from_dict(request_data)
	except Exception as e:
		raise HTTPException(
			status_code=400, detail={"message": f"Invalid request format: {str(e)}"}
		)

	if not request.recipe:
		raise HTTPException(
			status_code=400, detail={"message": "Missing required recipe data."}
		)

	try:
		recipe_dict = request.recipe.to_dict()

		system_prompt = (
			"You are an expert nutritional scientist. Calculate the macronutrients and total calories "
			"for the provided recipe. Output the nutrients for the whole recipe in total, not per portion. "
			"Evaluate ingredient quantities, units, and base portion sizes carefully. "
			"Ensure the output strictly mirrors the exact target JSON object fields."
		)

		structured_llm = llm.with_structured_output(LocalRecipeNutrients)

		messages = [
			SystemMessage(content=system_prompt),
			HumanMessage(
				content=f"Calculate exact macronutrients for this recipe payload: {recipe_dict}"
			),
		]

		with _tracer.start_as_current_span("llm.generate_nutrients"):
			response = await asyncio.wait_for(
				structured_llm.ainvoke(messages), timeout=60
			)

		return response.model_dump()

	except asyncio.TimeoutError:
		raise HTTPException(
			status_code=504, detail={"message": "LLM connection timed out."}
		)
	except Exception as e:
		traceback.print_exc()
		raise HTTPException(status_code=500, detail={"message": str(e)})
