[pytest]
pythonpath = .
testpaths = tests
addopts = -v
filterwarnings =
    ignore:Please use `import python_multipart` instead.:PendingDeprecationWarning
env =
    GOOGLE_APPLICATION_CREDENTIALS=dummy.json
    SERVICE_API_KEY=fake_key
    INTERNAL_AUTH_SECRET=test_secret_key_123